### PR TITLE
Tofe/work

### PR DESCRIPTION
**Pull request by Tofee**

### CODE REVIEW

**Comment by Herrie82** [comment]
Not 100% correct yet. The , . ' and - key have an issue with their annotation. Look at http://tinypic.com/r/2di0ozm/8

**Comment by Tofee** [comment]
Are you sure you took the latest code (with the latest PR I did) ? I get
this on my desktop: http://i.imgur.com/O7MAkru.png

**Comment by Herrie82** [comment]
Ah it was QtCreator having another project open still... On the email and URL/Search keyboard it's not correct, but that will probably just need some c&p from regular kb?

**Comment by Tofee** [comment]
Yes, it's still not correct on URL/Search, but it's not worse than before
either. It needs more work, for sure.

**Pull request merged**
