### PR TITLE
webos-keyboard: Fix whitespace mess

### PR DESCRIPTION
**Pull request by Herrie82**
Use spaces everywhere instead of mixing tabs with spaces.

### CODE REVIEW

**Comment by Tofee** [comment]
We lost some man-made alignments in the keyboards definitions, but overall it's a positive change. Let's merge it, and later on we can rework a bit these alignments in the QML files, if need be.

**Comment by Herrie82** [comment]
> We lost some man-made alignments in the keyboards definitions, but overall it's a positive change. Let's merge it, and later on we can rework a bit these alignments in the QML files, if need be.

Which ones? In general some of the strings were very long, might be good to put the items on individual lines just going forward, but that's for a next one.

**Comment by Tofee** [comment]
I was thinking about https://github.com/webOS-ports/webos-keyboard/pull/97/files#diff-39f3624d4c8ea13688680bfdf7431d738fc39dca4bcaf9f64b33bdd1850cae6fL152-R162 for instance

**Comment by Tofee** [comment]
Probably yes; and as we quite never touch that part, it's quite fine if the structure isn't crystal-clear :)

**Pull request merged**
